# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tblaudez <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/04/04 10:04:32 by tblaudez          #+#    #+#              #
#    Updated: 2018/04/04 10:04:34 by tblaudez         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRCS = ft_display_file.c

all : $(NAME)

$(NAME) : 
	@gcc -Wall -Wextra -Werror -o $(NAME) $(SRCS)

clean : 
	@:

fclean : clean
	rm -f $(NAME)

re : fclean all